import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import "./styles/preview.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "./components/nav-foot/NavBar";
import Providers from "./provider";
import Footer from "./components/nav-foot/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased min-h-screen flex flex-col bg-gray-50`}
      >
        <Providers>
          <Theme accentColor="plum" grayColor="gray">
            <NavBar />

            <main className="flex-1 pb-24 pt-10">{children}</main>

            <Footer />
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
