import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "./components/NavBar";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <Providers>
          <Theme accentColor="plum" grayColor="gray">
            <NavBar />
            <main>{children}</main>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
